setwd("\\Users\\noelm\\Desktop\\Saadhangal\\STUDY STEFF\\RSET\\CLASSES\\S2\\RP LAB\\Codes")
dataf<-read.csv("emp.csv")
dataf
print(is.data.frame(dataf))
print(ncol(dataf))
print(nrow(dataf))
print(max(dataf$salary))
r<-subset(dataf, salary == max(salary))
print(r)
q<-subset(dataf,dept=="IT")
print(q)
t<-subset(dataf,as.Date(start_date)>as.Date("2014-01-01"))
print(t)
write.csv(t,"output.csv")
newdataf<-read.csv("output.csv")
newdataf
